.\" "$Id: dwww-format-man.8,v 1.13 2006-06-04 14:38:18 robert Exp $"
.\" 
.TH DWWW\-FORMAT\-MAN 8 "June 4th, 2006" "dwww 1.10.0" "Debian"
.SH NAME
dwww\-format\-man \- batch format manual pages for dwww
.SH SYNOPSIS
.BR dwww\-format\-man " [" \-v | \-\-verbose ]
.I directory
.I ...
.SH DESCRIPTION
.B dwww\-format\-man
looks for manual pages in the directories named on the command line.
It formats each manual page, and puts the formatted version into the
dwww document cache.
System administrator's can run
.B dwww\-format\-man
if they want to make it faster to retrieve manual pages via dwww.
If
.B dwww\-format\-man
is not run, dwww will automatically format manual pages not in its cache.
Long pages take a few moments to format,
but rarely so slow that it is worth running.
.PP
.B dwww\-format\-man 
runs 
.BR dwww\-convert (8)
with privileges of DWWW_CGIUSER (see 
.BR dwww (8).
.SH "OPTIONS"
.TP
.BR \-v ", " \-\-verbose
Print each proceeded file name.
.SH "SEE ALSO"
.BR dwww (8), 
.BR dwww\-convert (8).
.SH AUTHOR
Lars Wirzenius <liw@iki.fi>.
Slightly modified by Robert Luberda <robert@debian.org>.
.br
See
.BR dwww (8)
for copyrights and stuff.
