.\" $Id: dwww-quickfind.8 531 2009-02-15 12:54:08Z robert $
.TH DWWW\-QUICKFIND 8 "February 15th, 2009" "dwww 1.11.1" "Debian"
.SH NAME
dwww\-quickfind \- find quickly which package a program belongs to.
.SH SYNOPSIS
.BI "dwww\-quickfind \-\-build " "dbfile"
.br
.BI "dwww\-quickfind " "program"
.I "dbfile"
.SH DESCRIPTION
.B dwww\-quickfind
is part of the dwww package,
which provides access to on\-line documentation on a Debian system via WWW.
.PP
.B dwww\-quickfind
searches for
.I program
using the database file
.I dbfile.
If used with
.BR "\-\-build" ,
.B dwww\-quickfind
builds programs database and stores it in  the file
.IR dbfile .
.SH FILES
.TP
.I /var/cache/dwww/quickfind.dat
Default file used as the database file.
.SH "SEE ALSO"
.BR dwww (7),
.BR dwww\-find (8).
.SH AUTHOR
Lars Wirzenius.
.br
See
.BR dwww (7)
for copyrights and stuff.
