.\" "$Id: dwww-build-menu.8 531 2009-02-15 12:54:08Z robert $"
.\"
.TH DWWW\-BUILD\-MENU 8 "February 15th, 2009" "dwww 1.11.1" "Debian"
.SH NAME
dwww\-build\-menu \- builds dwww Debian Documentation Menu
.\"
.SH SYNOPSIS
.B  dwww\-build\-menu
.\"
.SH DESCRIPTION
.PP
.B dwww\-build\-menu
is part of the dwww package,
which provides access to on\-line documentation on a Debian system via WWW.
.PP
.B dwww\-build\-menu
generates the Debian Documentation Menu pages
(available on
.IR http://localhost/dwww/menu/ ),
from files registered with doc\-base program, found in the
.I /var/lib/doc\-base/documents
.\"
.PP
The generated pages are stored in DWWW_DOCROOTDIR/dwww/menu directory. (Default is
.IR /var/www/dwww/menu .)
.SH FILES
.TP 
.I /etc/dwww/dwww.conf
Configuration file for dwww.
.TP
.I /var/www/dwww/menu
Default directory for generated menu pages.
.TP
.I /var/lib/dwww
Temporary directory used while generating the pages.
.\"
.SH "SEE ALSO"
.BR dwww (7),
.BR dwww\-build (8),
.BR install\-docs (8),
.RI "Debian doc\-base Manual in " /usr/share/doc/doc\-base/doc\-base.html/index.html .
.\"
.SH AUTHOR
Robert Luberda <robert@debian.org>.
See
.BR dwww (7)
for copyrights and stuff.
