.\" $Id: dwww-convert.8,v 1.8 2003-03-06 22:47:04 robert Exp $
.TH DWWW\-CONVERT 8 "March 6th, 2003" "dwww 1.9.0" "Debian"
.SH NAME
dwww\-convert \- convert files to HTML for dwww
.SH SYNOPSIS
.BI "dwww\-convert " type
.I location
.SH "DESCRIPTION"
.B dwww\-convert
is part of the dwww package,
which provides access to on-line documentation on a Debian system via WWW.
.B dwww\-convert
converts documentation to HTML so that it can be viewed with a WWW browser.
.B dwww\-convert
is usually run by the WWW server, but can also be run by hand.
.PP
The
.I type
argument gives the type of the file, one of:
.IP file
An arbitrary file; the type is guessed using simple heuristics based on
the filename.
.IP dir
A directory.  If the directory contains the file
.IR index.html " or " index.htm
that file will be returned. Otherwise,
A listing of the files in the directory is generated.
.IP html
An HTML file.  The file is returned as is.
.IP man
A manual page.  The location is the pathname of the nroff source file.
.IP runman
A manual page.  The location is the name of the manual page and its
section, separated by a slash.  For example,
the location would be
.B intro/1
to refer to the
.BR  intro (1)
manual page.
.IP info
An Info file.
.IP text
A plain text file (using the ISO\-8859\-1 character set).
.PP
An unknown file type is treated as
.BR text .
.PP
The
.I location
argument gives the filename of the file.
The name must be complete, i.e., it must start at the root directory (/).
The name must not contain any symbolic links (cf.
.BR realpath (1)).
The file must be located in or below a directory that has been allowed
by the system administrator; see
.BR dwww (8)
for more info.
.PP
The file may be compressed with
.BR gzip (1)
or
.BR bzip2 (1).
It is uncompressed automatically and invisibly.
Compression is indicated by a filename that ends in `.gz' or `.bz2'.
.SH FILES
.TP
.I /etc/dwww/dwww.conf
Configuration file for dwww.  See
.BR dwww (8)
for more information.
.SH "SEE ALSO"
.BR dwww (8),
.BR dwww\-txt2html (8),
.BR dwww\-build (8),
.BR dwww\-cache (8).
.SH AUTHOR
Lars Wirzenius.
Modified by Robert Luberda.
.br
See
.BR dwww (8)
for copyrights and stuff.
