.\" "@(#)dwww:$Id: dwww.8,v 1.11 2002/04/25 07:04:09 robert Exp $"
.\"
.TH dwww 8 "April 25th, 2002" "dwww 1.7.5" "Debian"
.SH NAME
dwww \- access documentation via WWW
.SH SYNOPSIS
http://localhost/dwww/index.html
.SH DESCRIPTION
A typical Linux system has documentation in many formats (manual pages,
Info files, READMEs, and so on).
dwww makes it possible to access all of these via the same interface,
a WWW browser.
This makes it easier to use the documentation.
.PP
dwww consists of several programs:
.TP
.B cgi-bin/dwww
Run by the WWW server when user requests document via dwww.
Parses the request and runs dwww-convert with suitable arguments.
Installed in the servers cgi-bin directory.
.TP
.BR dwww-convert (8)
Converts any document to HTML.
.TP
.BR dwww-cache (8)
Manages the cache of converted documents.
.TP
.BR dwww-build (8)
Builds static lists of manual pages.
Needs to be re-run whenever documents are installed or removed.
.PP
For speed reasons, the converted documents are stored in
.IR /var/cache/dwww .
The cache is cleaned of old documents to keep it from growing too large.

.PP
.SH CONFIGURATION
dwww is configured via the
.I /etc/dwww/dwww.conf
file.
That file is a Bourne shell
.RI ( /bin/sh )
script that defines some or all the following variables
(defaults are used if the file doesn't exist,
or doesn't define the variable).
.\"
.SS Basic configuration variables
These variables can be also configured by debconf script. You can change
them using the following command:
.RS
.I dpkg-reconfigure dwww
.RE
.IP DWWW_SERVERNAME
Name of the www server.
Default is
.BR localhost .
.\"
.IP DWWW_SERVERPORT
Port on which the www server listen to.
Default is
.BR 80 .
.\"
.IP DWWW_DOCROOTDIR
The document root for web server.
.\"
.IP DWWW_CGIDIR
The directory which contains the CGI scripts for your web server.
.\"
.IP DWWW_CGIUSER
Name of the user that the web server uses to execute CGI scripts.
Default is
.BR www-data .
.\"
.SS Browser variables
.IP DWWW_BROWSER 
Web-browser used by
.BR dwww (1)
to load dwww main page.
.IP DWWW_X11_BROWSER 
Web-browser used by
.BR dwww (1)
to load dwww main page when in X11.
.\"
.SS Path variables
.IP DWWW_DOCPATH
Colon-delimited list of directories from which
.BR dwww-convert (8)
supplies files.  For security reasons, it will refuse to convert files
outside the directories named by this variable.
Default is
.IR /usr/share/doc:/usr/doc:/usr/share/info:/usr/info:
.IR /usr/share/man:/usr/man:/usr/X11R6/man:/usr/local/man:
.IR /usr/local/doc:/usr/local/info:/usr/share/common-licenses .
.\"
.IP DWWW_ALLOWEDLINKPATH
Colon-delimited list of directories which can be targets of symlinks from
files from directories inside \fIDWWW_DOCPATH\fR.
Default value is
.IR /usr/share:/usr/lib .
.br
For example, \fI/usr/share/doc/package/foo.html\fR may be symlinked to a file
\fI/usr/share/package/foo.html\fR, and this file can be displayed by
.BR dwww .
.SS Converters
.IP DWWW_MAN2HTML
Command to convert a manual page to HTML.
Default is
.BR builtin_man2html ,
which uses 
.BR dwww-txt2html (8)
to convert manpages.
.br
If you have
.BR man2html (8)
installed and would prefer to use it, please add the following code
to dwww's configuration file:
.RS
.nf

if [ -x /usr/lib/cgi-bin/man2html ] ; then
    man2html_cmd () {
        /usr/lib/cgi-bin/man2html "$1"
    }
    DWWW_MAN2HTML=man2html_cmd
fi

.fi
.RE
.\"
.IP DWWW_TEXT2HTML
Command to convert a plain text file to HTML.
Default is
.BR builtin_text2html .
.\"
.IP DWWW_DIR2HTML
Command to show contents of a directory as HTML.
Default is
.BR builtin_dir2html .
.PP
The converters get the filename as their argument,
and should output the converted document to stdout.
.SS Other variables
.\"
.IP DWWW_KEEPDAYS
How many days should
.I /etc/cron.daily/dwww
keep documents that have not been accessed?
Default is 
.B 10
days.
.\"
.IP DWWW_HTMLDIR
Directory where
.BR dwww-build (8)
stores the web pages it generates.
Default is
.IR /var/lib/dwww .
.IP DWWW_USEFILEURL
If this variable is set, dwww will use file:/ style URL's to
access html files -- bypassing the cgi script.  This is faster
on slow machines.  Of course, you will not be able to read
the html documentation on a non-local machine.  Default is
to not enable this feature.
.\"
.IP DWWW_TITLE
Title to appear on dwww generated files.
Default is
.BR "dwww: $(hostname)"
.\"
.IP DWWW_USE_CACHE
If this variable is set to 
.B "yes" 
(default), dwww will cache files in 
/var/cache/dwww. See 
.BR dwww-cache (8).
.SH FILES
.IP /etc/dwww/dwww.conf
Configuration file for dwww.
It's not necessary for this file to exist,
there are sensible defaults for everything.
.IP /var/cache/dwww
Cache for the converted documents.
.IP /usr/share/dwww
Templates for the dwww web pages (used by
.BR dwww-build (8)).
.IP /var/lib/dwww
The dwww pages.
The server's document root directory should have a link to
this directory.
.SH "SEE ALSO"
.BR dwww (1),
.BR dwww-convert (8),
.BR dwww-build (8),
.BR dwww-cache (8),
.BR dwww-format-man (8),
.BR dwww-txt2html (8),
.BR dwww-quickfind (8),
.BR dwww-find (8).
.SH AUTHOR
Originally by Lars Wirzenius <liw@iki.fi>.
Modified by Jim Pick <jim@jimpick.com> and Robert Luberda <robert@debian.org>.
Bugs should be reported via the normal Debian bug reporting system.
.PP
dwww is licensed via the GNU General Public License.
While it has been written for Debian, porting it to other
systems is strongly encouraged.
